Fix AttributeError: 'ClientConnectorCertificateError' object has no attribute '_os_error'. (#12136)
(cherry picked from commit c0f1513c37cb145b2618aeffd8f58d2f0cf230ab)