fix syntax in same key example
>>> d = MultiDict[('a', 1), ('b', 2), ('a', 3)])
  File "<ipython-input-2-f83c203956e2>", line 1
    d = MultiDict[('a', 1), ('b', 2), ('a', 3)])
                                           ^
SyntaxError: invalid syntax

After adding the missing '(' between 't' and '[':
>>> d = MultiDict([('a', 1), ('b', 2), ('a', 3)])
>>> d
<MultiDict('a': 1, 'b': 2, 'a': 3)>