Increase the upper boundary of the multidict dependency allowing v6
The `multidict` dependency used to be `multidict >=4.5, < 7.0` in `aiohttp` v3.8.1,
but was pinned down to `multidict >=4.5, < 6.0` in `aiohttp` v3.8.2
(https://github.com/aio-libs/aiohttp/pull/6550) in an attempt to help avoid
new errors.

However, https://github.com/python/bedevere/ uses `multidict==6.0.2`
so the requirements resolution fails with `aiohttp==3.8.2`:

```console
ERROR: Cannot install -r requirements.txt (line 1) and multidict==6.0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested multidict==6.0.2
    aiohttp 3.8.2 depends on multidict<6.0 and >=4.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

https://github.com/hugovk/bedevere/actions/runs/3095794573/jobs/5010600772

This patch makes it possible to have `multidict` v6 installed in the same env as `aiohttp` v3.8.3, as with `aiohttp` v3.8.1.

Partially related to closed https://github.com/aio-libs/aiohttp/issues/6600 and
merged https://github.com/aio-libs/aiohttp/pull/6550.

PR #6950

Co-Authored-By: Sviatoslav Sydorenko <webknjaz@redhat.com>